### ISSUE TITLE
r2p_R2Power.SelectableDraggableSVG is missing in SelectSVG solution

### ISSUE THREAD

**Issue by e-gallis** [PowerRobin/FunWithSVGs#1]
Hi Robin,
I am trying to open your demo app (https://github.com/PowerRobin/FunWithSVGs/blob/main/PowerApps%20CC%20SVG%20demo.msapp).
Before opening it I installed your **SelectSVG** solution.
But after installing the solution, when I try to open the demo app, it says that the following component is missing: **r2p_R2Power.SelectableDraggableSVG**
Indeed, I don't see it in the solution.
Am I doing something wrong?
Thanks,
Emmanuel

**Comment by PowerRobin** [comment]
oh, hey I'm sorry.
I actually didn't know that the component needed to be in a solution, I
thought it's stored in the app...

Thanks for letting me know, packed everything into a solution and uploaded
again:
https://github.com/PowerRobin/FunWithSVGs/blob/main/PowerAppCC_Demo_Solution.zip

Please let me know if it doesn't work.



Am Mi., 16. Feb. 2022 um 21:56 Uhr schrieb Emmanuel GALLIS <
***@***.***>:

**Comment by e-gallis** [comment]
Ok, now I have the drag component in the solution. But even though I created a Bin Maps account, generated a key and created a connexion in Power Apps, when I launch your demo app the system doesn't seem to detect the Bin Maps connexion and I can't acknowledge it... Any ideas on this particular issue?
![image](https://user-images.githubusercontent.com/32480338/154495695-7c7488b1-8f9b-4cf0-8c9a-43acd0eab72e.png)

**Comment by e-gallis** [comment]
And also, in the SelectSVG demo app, when I click on the first hamburger menu to go to the Icons screen it shows a blank screen:
![image](https://user-images.githubusercontent.com/32480338/154500730-dcc834b7-d4ff-447b-b55f-014d16566c0b.png)
Just made another test: it works fine if I edit the app, but on the published app it shows me an empty screen... 😲

**Comment by e-gallis** [comment]
Opening your SelectSVG demo app, on the technical drawing app, I notice that within the Studio I can't click on elements on the SVG. Does this work only in published app? If yes this means you can't test it in Studio?

**Comment by PowerRobin** [comment]
Hey Emmanuel,

thanks for your feedback!
I uploaded the solution again without the Bing Maps Connection, which
wasn't used anymore.

The Icons-Example works fine for me - do you see anything there (like the
buttons & toggle on the right?)

And to your other question - yes, sadly the Select-functionality doesn't
work in the edito - only in the published app.

Hope you can open it now - if not, let me know!

Cheers
Robin

Am Do., 17. Feb. 2022 um 15:36 Uhr schrieb Emmanuel GALLIS <
***@***.***>:

**Comment by e-gallis** [comment]
Ok, now the Bing Maps connector has disappeared so this is fixed... 👍

The icons screen is still empty when I jump to it from the published app... Really really strange:
![BugIconsEmpty](https://user-images.githubusercontent.com/32480338/154935927-cbcffbfa-7a99-4f03-9071-35df09df95f9.gif)
Don't bother though... Not a big deal!

Really too bad that the Select feature is not working in the Studio. I'll ask the Power Apps team why is that.

I'll close this issue now... Thank for your help. Appreciated! 🙏👍
